### PR TITLE
Update to RenClouds V1.12 scs-sdk-plugin

### PR DESCRIPTION
**Pull request by DTheIcyDragon**
### Additions
- Added Comments to the zones, which allow easier maintaining since Renclouds commants are in the same place
- Added Missing Values and changed Empty Buffers accordingly
### Changes
- Changed Version Number
- Changed Readme to the newest Versions

### CODE REVIEW

**Comment by Dreagonmon** [comment]
Thanks for PR, I will review it as soon as possible.

**Comment by Dreagonmon** [comment]
I changed some of the code, but I can't test it now.

 If it works, I can merge it.

**Comment by DTheIcyDragon** [comment]
I'll test this today and tell you if it works

**Comment by DTheIcyDragon** [comment]
as far as I saw it all works as intended, It selects the right version all on its own and returns all the data according to it

**Pull request merged**
